# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Project
mod_version=1.0.0-SNAPSHOT
group=com.holybuckets.ruinmap

# Common
minecraft_version=1.20.1

# Forge
forge_version=47.3.0
forge_loader_version_range=[47,)
forge_version_range=[47,)
minecraft_version_range=[1.20.1, 1.21)

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.15.10
loom_version=1.7-SNAPSHOT

# Mod options
mod_name=HBs_Ruin_Map
mod_author=Holy_Buckets
mod_id=hbs_ruinmap
license=GNUv3
description=Adds special treasure maps that lead you to new structures; gateway structures that teleport you to bosses.

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependencies
gson_version=2.8.9
antlr_version=4.9.3
sqlite_version=3.46.1.0
balm_version=7.3.41+1.20.1
balm_version_range=[7.3.37,)
#balm_version=1.0.6-SNAPSHOT
foundation_version=1.8.46-SNAPSHOT
foundation_min_version=1.6.17

chunkload_version=1.1.2-SNAPSHOT
chunkload_min_version=1.1.1

create_version=6.0.8
create_forge_version=6.0.8-289
create_fabric_version=6.0.8.1+build.1744-mc1.20.1
create_proj_id=328085
create_fabric_proj_id=624165
create_fabric_file_id=7286603
create_forge_file_id=7178761

# Forge-only, compile-time-only mods (CurseForge)
chunkpregenerator_project_id=267193
chunkpregenerator_file_id=5216892

# Publishing
release_dir=C:/Users/jack/Desktop/docs/11_Minecraft/00-Releases